[debug] [2021-06-08T09:40:38.711Z] ----------------------------------------------------------------------
[debug] [2021-06-08T09:40:38.714Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2021-06-08T09:40:38.714Z] CLI Version:   9.12.1
[debug] [2021-06-08T09:40:38.715Z] Platform:      win32
[debug] [2021-06-08T09:40:38.715Z] Node Version:  v12.19.0
[debug] [2021-06-08T09:40:38.716Z] Time:          Tue Jun 08 2021 16:40:38 GMT+0700 (Indochina Time)
[debug] [2021-06-08T09:40:38.716Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-06-08T09:40:38.719Z] >>> [apiv2][query] GET https://firebase-public.firebaseio.com/cli.json [none]
[debug] [2021-06-08T09:40:38.746Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-06-08T09:40:38.747Z] > authorizing via signed-in user (dtc16hd4801030001@ictu.edu.vn)
[debug] [2021-06-08T09:40:38.747Z] [iam] checking project getdataai for permissions ["firebase.projects.get"]
[debug] [2021-06-08T09:40:38.748Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-06-08T09:40:38.749Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-06-08T09:40:38.993Z] <<< HTTP RESPONSE 200 {"pragma":"no-cache","cache-control":"no-cache, no-store, max-age=0, must-revalidate","expires":"Mon, 01 Jan 1990 00:00:00 GMT","date":"Tue, 08 Jun 2021 09:41:12 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-06-08T09:40:39.018Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/getdataai:testIamPermissions  
 {"permissions":["firebase.projects.get"]}
[debug] [2021-06-08T09:40:39.573Z] <<< [apiv2][status] GET https://firebase-public.firebaseio.com/cli.json 200
[debug] [2021-06-08T09:40:39.574Z] <<< [apiv2][body] GET https://firebase-public.firebaseio.com/cli.json {"cloudBuildErrorAfter":1594252800000,"cloudBuildWarnAfter":1590019200000,"defaultNode10After":1594252800000,"minVersion":"3.0.5","node8DeploysDisabledAfter":1613390400000,"node8RuntimeDisabledAfter":1615809600000,"node8WarnAfter":1600128000000}
[debug] [2021-06-08T09:40:40.131Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Tue, 08 Jun 2021 09:41:13 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=892","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-06-08T09:40:40.132Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project getdataai:

  firebase.projects.get
[debug] [2021-06-08T09:40:40.133Z] > refreshing access token with scopes: []
[debug] [2021-06-08T09:40:40.133Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-06-08T09:40:40.420Z] <<< HTTP RESPONSE 200 {"cache-control":"no-cache, no-store, max-age=0, must-revalidate","date":"Tue, 08 Jun 2021 09:41:13 GMT","expires":"Mon, 01 Jan 1990 00:00:00 GMT","pragma":"no-cache","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-06-08T09:40:40.493Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/getdataai [none]
[debug] [2021-06-08T09:40:41.084Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/getdataai 403
[debug] [2021-06-08T09:40:41.084Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/getdataai {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2021-06-08T09:40:41.086Z] HTTP Error: 403, The caller does not have permission
[debug] [2021-06-08T09:40:41.343Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at module.exports (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:38:12)
    at Client.doRequest (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:238:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.request (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:96:20)
    at async Object.getFirebaseProject (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\management\projects.js:290:21)
    at async getProjectNumber (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\getProjectNumber.js:11:22)
    at async C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\command.js:169:17
[error] 
[error] Error: Failed to get Firebase project getdataai. Please make sure the project exists and your account has permission to access it.
[debug] [2021-06-08T09:40:57.924Z] ----------------------------------------------------------------------
[debug] [2021-06-08T09:40:57.926Z] Command:       C:\Program Files\nodejs\node.exe C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\bin\firebase.js serve
[debug] [2021-06-08T09:40:57.926Z] CLI Version:   9.12.1
[debug] [2021-06-08T09:40:57.926Z] Platform:      win32
[debug] [2021-06-08T09:40:57.926Z] Node Version:  v12.19.0
[debug] [2021-06-08T09:40:57.928Z] Time:          Tue Jun 08 2021 16:40:57 GMT+0700 (Indochina Time)
[debug] [2021-06-08T09:40:57.928Z] ----------------------------------------------------------------------
[debug] 
[debug] [2021-06-08T09:40:57.937Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2021-06-08T09:40:57.938Z] > authorizing via signed-in user (dtc16hd4801030001@ictu.edu.vn)
[debug] [2021-06-08T09:40:57.938Z] [iam] checking project getdataai for permissions ["firebase.projects.get"]
[debug] [2021-06-08T09:40:57.941Z] > refreshing access token with scopes: ["email","https://www.googleapis.com/auth/cloud-platform","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","openid"]
[debug] [2021-06-08T09:40:57.941Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-06-08T09:40:58.269Z] <<< HTTP RESPONSE 200 {"cache-control":"no-cache, no-store, max-age=0, must-revalidate","date":"Tue, 08 Jun 2021 09:41:31 GMT","pragma":"no-cache","expires":"Mon, 01 Jan 1990 00:00:00 GMT","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-06-08T09:40:58.347Z] >>> HTTP REQUEST POST https://cloudresourcemanager.googleapis.com/v1/projects/getdataai:testIamPermissions  
 {"permissions":["firebase.projects.get"]}
[debug] [2021-06-08T09:40:59.425Z] <<< HTTP RESPONSE 200 {"content-type":"application/json; charset=UTF-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","date":"Tue, 08 Jun 2021 09:41:32 GMT","server":"ESF","cache-control":"private","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","server-timing":"gfet4t7; dur=961","alt-svc":"h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-06-08T09:40:59.427Z] [iam] error while checking permissions, command may fail: FirebaseError: Authorization failed. This account is missing the following required permissions on project getdataai:

  firebase.projects.get
[debug] [2021-06-08T09:40:59.430Z] > refreshing access token with scopes: []
[debug] [2021-06-08T09:40:59.430Z] >>> HTTP REQUEST POST https://www.googleapis.com/oauth2/v3/token  
 <request body omitted>
[debug] [2021-06-08T09:40:59.667Z] <<< HTTP RESPONSE 200 {"expires":"Mon, 01 Jan 1990 00:00:00 GMT","pragma":"no-cache","date":"Tue, 08 Jun 2021 09:41:33 GMT","cache-control":"no-cache, no-store, max-age=0, must-revalidate","content-type":"application/json; charset=utf-8","vary":"X-Origin, Referer, Origin,Accept-Encoding","server":"scaffolding on HTTPServer2","x-xss-protection":"0","x-frame-options":"SAMEORIGIN","x-content-type-options":"nosniff","alt-svc":"h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000,h3-T051=\":443\"; ma=2592000,h3-Q050=\":443\"; ma=2592000,h3-Q046=\":443\"; ma=2592000,h3-Q043=\":443\"; ma=2592000,quic=\":443\"; ma=2592000; v=\"46,43\"","accept-ranges":"none","transfer-encoding":"chunked"}
[debug] [2021-06-08T09:40:59.723Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/getdataai [none]
[debug] [2021-06-08T09:41:00.269Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/getdataai 403
[debug] [2021-06-08T09:41:00.269Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/getdataai {"error":{"code":403,"message":"The caller does not have permission","status":"PERMISSION_DENIED"}}
[debug] [2021-06-08T09:41:00.270Z] HTTP Error: 403, The caller does not have permission
[debug] [2021-06-08T09:41:00.478Z] FirebaseError: HTTP Error: 403, The caller does not have permission
    at module.exports (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\responseToError.js:38:12)
    at Client.doRequest (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:238:23)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Client.request (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\apiv2.js:96:20)
    at async Object.getFirebaseProject (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\management\projects.js:290:21)
    at async getProjectNumber (C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\getProjectNumber.js:11:22)
    at async C:\Users\5SCOMPUTER\AppData\Roaming\npm\node_modules\firebase-tools\lib\command.js:169:17
[error] 
[error] Error: Failed to get Firebase project getdataai. Please make sure the project exists and your account has permission to access it.
